-- Schema Standardization Migration
-- Purpose: Fix duplicate/redundant columns and standardize naming conventions
-- Date: 2026-01-01
-- Ticket: Schema cleanup for production readiness

-- ============================================================================
-- 1. TENANTS TABLE: Consolidate email/phone columns
-- ============================================================================

-- Copy owner_email/owner_phone to business_email/business_phone if business_ columns are null
UPDATE tenants
SET 
  business_email = COALESCE(business_email, owner_email),
  business_phone = COALESCE(business_phone, owner_phone)
WHERE business_email IS NULL OR business_phone IS NULL;

-- Make business_email/business_phone NOT NULL (since they're the source of truth)
ALTER TABLE tenants
ALTER COLUMN business_email SET NOT NULL;

-- Drop the old owner_email/owner_phone columns (after copying data)
-- COMMENTED OUT FOR SAFETY - uncomment after verifying data is copied correctly
-- ALTER TABLE tenants DROP COLUMN IF EXISTS owner_email;
-- ALTER TABLE tenants DROP COLUMN IF EXISTS owner_phone;

-- ============================================================================
-- 2. TIME_SLOTS TABLE: Document which columns are used
-- ============================================================================

-- Add comments to clarify column usage
COMMENT ON COLUMN time_slots.slot_time IS 'Primary slot time (used in queries and orders)';
COMMENT ON COLUMN time_slots.is_active IS 'Admin-controlled active flag (used in availability checks)';
COMMENT ON COLUMN time_slots.max_orders IS 'Maximum orders allowed for this slot';
COMMENT ON COLUMN time_slots.current_orders IS 'Current count of booked orders (atomic counter)';
COMMENT ON COLUMN time_slots.fulfillment_type IS 'pickup or delivery';
COMMENT ON COLUMN time_slots.generated_by_template IS 'TRUE if auto-generated by slot template';
COMMENT ON COLUMN time_slots.is_overridden IS 'TRUE if admin manually edited this slot';

-- TODO: Verify if start_time, end_time, duration_minutes, is_available are used
-- If not used, they should be dropped in a future migration after code audit

-- ============================================================================
-- 3. ADD SCHEMA VERSION TRACKING
-- ============================================================================

CREATE TABLE IF NOT EXISTS schema_migrations_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  migration_file TEXT NOT NULL,
  applied_at TIMESTAMPTZ DEFAULT NOW(),
  description TEXT,
  applied_by TEXT DEFAULT current_user
);

INSERT INTO schema_migrations_log (migration_file, description)
VALUES ('2026-01-01-schema-standardization.sql', 'Consolidated tenants email/phone columns, documented time_slots columns');

-- ============================================================================
-- 4. VERIFY DATA INTEGRITY
-- ============================================================================

-- Check for any tenants without business_email (should be 0 after this migration)
DO $$
DECLARE
  missing_count INT;
BEGIN
  SELECT COUNT(*) INTO missing_count
  FROM tenants
  WHERE business_email IS NULL;
  
  IF missing_count > 0 THEN
    RAISE WARNING 'Found % tenants without business_email - manual intervention needed', missing_count;
  ELSE
    RAISE NOTICE 'All tenants have business_email ✓';
  END IF;
END $$;

